version: '3.8'

services:
  luna-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luna-voice-bot
    restart: unless-stopped
    
    # Resource limits for optimization
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    
    # Volumes for persistent data
    volumes:
      - ./voicefiles:/app/voicefiles:rw
      - ./config/settings.py:/app/config/settings.py:ro
    
    # Network mode (use host network for better Discord connectivity)
    network_mode: bridge
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Optional: Redis for caching (uncomment if needed)
# redis:
#   image: redis:7-alpine
#   container_name: luna-redis
#   restart: unless-stopped
#   deploy:
#     resources:
#       limits:
#         memory: 128M
#         cpus: '0.1'
#   volumes:
#     - redis_data:/data
#   command: redis-server --appendonly yes

# volumes:
#   redis_data:
